/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getActiveDisplayCount(): number
export function takeScreenshot(x: number, y: number, width: number, height: number, id?: number | undefined | null): ImageData
export function mouseMove(x: number, y: number): void
export const enum ColorType {
  RGBA = 0,
  BGRA = 1
}
export interface Point {
  x: number
  y: number
}
export function saveImageData(imageData: ImageData, path: string): Promise<void>
export function readImageData(path: string): Promise<ImageData>
export function imageSearch(source: ImageData, target: ImageData, variant?: number | undefined | null): Promise<Point | null>
export class ImageData {
  data: Array<number>
  width: number
  height: number
  colorType: ColorType
  pixelWidth: number
}
